name: news
description: A new Flutter application For latest News.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  get_it: ^3.0.3
  url_launcher:
  splashscreen: ^1.3.5
  carousel_slider: ^3.0.0
  share: 2.0.1
  path_provider: ^0.4.1
  flutter_launcher_icons: ^0.9.0


dev_dependencies:

  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"



flutter:


  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/news-news-image.png


  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
    - family: ViaodaLibre
      fonts:
        - asset: assets/fonts/ViaodaLibre-Regular.ttf



